# CBT Model Overrides Configuration
#
# This file allows you to override CBT transformation model configurations
# without modifying the source models in xatu-cbt.
#
# IMPORTANT: xcli automatically generates default overrides with a backfill limit
# (default: 2 weeks, configurable in .xcli.yaml) to prevent backfilling from genesis
# in hybrid mode. This file is OPTIONAL and only needed if you want to customize
# specific models or change the default limit.
#
# How it works:
# 1. xcli calculates configured duration ago (e.g., "2w" = 2 weeks)
#    - For known networks (mainnet, sepolia, hoodi): uses slot numbers
#    - For custom networks: uses Unix timestamps (or add genesisTimestamp to .xcli.yaml)
# 2. User overrides in this file take precedence over the generated defaults
# 3. Final merged config is written to .xcli/configs/cbt-overrides-{network}.yaml
#
# Docs: https://github.com/ethpandaops/cbt?tab=readme-ov-file#model-overrides

# Optional: Override the default 2-week backfill limit
# Leave commented to use auto-generated 2-week limit
# defaultLimits:
#   min: 10000000  # Custom position (slot number or Unix timestamp depending on model)
#   max: 0         # No upper limit (0 = unlimited)

# Per-model overrides - customize specific models
models:
  # Example: Override a specific model's limits
  fct_block:
    config:
      limits:
        min: 9500000  # Custom start position for this model
      schedules:
        forwardfill: "@every 1m"
        backfill: "@every 5m"

  # Example: Disable an expensive or unwanted model
  fct_address_storage_slot_total:
    enabled: false

  # Example: Override just the schedule
  fct_attestation_first_seen_chunked_50ms:
    config:
      schedules:
        forwardfill: "@every 10s"  # Less frequent in dev
        backfill: "@every 2m"

# Common configurations for different scenarios:
#
# Local development (fast iteration, limited data):
#   defaultLimits:
#     min: 10000000
#     max: 10010000  # Only process 10,000 slots
#
# Hybrid mode (connect to prod, backfill recent data only):
#   defaultLimits:
#     min: 10000000  # Start from recent slot (e.g., ~few months ago)
#     max: 0         # No upper limit
#
# Testing specific models:
#   models:
#     model_to_test:
#       config:
#         limits:
#           min: 10000000
#           max: 10001000
#     # Disable all other expensive models
#     other_model:
#       enabled: false
